extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:jsx-a11y/recommended
env:
  browser: true
  es6: true
settings:
  react:
    version: detect

overrides:
  - files: ["*.ts", "*.tsx"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      sourceType: module
      ecmaFeatures:
        jsx: true
    extends:
      - plugin:react/recommended
      - plugin:@typescript-eslint/recommended
    plugins:
      - "@typescript-eslint"
      - react
      - import
    rules:
      "import/no-default-export": error
      "no-console":
        - error
        - allow:
            - info
            - warn
            - error
      "@typescript-eslint/no-explicit-any": "off"
      "react/prop-types": "off"
      "no-unused-vars": "off"
      "react/react-in-jsx-scope": "off"
